[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "flask-cors>=6.0.1",
    "mcp[cli]>=1.13.1",
    "openai>=1.101.0",
    "python-dotenv>=1.1.1",
]
